# Generated by Django 5.1.4 on 2025-01-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_customuser_user_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_of_case', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(blank=True, max_length=50, null=True)),
                ('court_no', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.district')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.state')),
                ('court_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.court_type')),
            ],
        ),
    ]
