# Generated by Django 5.1.4 on 2025-01-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_case_stage_case_type_court_type_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.court_type'),
        ),
        migrations.AlterField(
            model_name='court',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.district'),
        ),
        migrations.AlterField(
            model_name='court',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.state'),
        ),
    ]
