# Generated by Django 5.1.4 on 2025-01-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='client_id',
        ),
    ]
