# Generated by Django 5.1.4 on 2025-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_sub_advocate_case_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_master',
            name='sub_advocate',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case_master',
            name='comments',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Sub_advocate',
        ),
    ]
