# Generated by Django 5.1.4 on 2025-01-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_alter_case_master_sub_advocate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_master',
            name='case_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='case_master',
            name='fir_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
