# Generated by Django 5.1.4 on 2025-01-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_alter_case_master_case_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case_Master',
        ),
    ]
