# Generated by Django 5.1.4 on 2025-01-29 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_delete_case_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('crn', models.CharField(blank=True, max_length=50, null=True)),
                ('case_no', models.CharField(blank=True, max_length=50, null=True)),
                ('case_year', models.CharField(blank=True, max_length=4, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('court_type', models.CharField(blank=True, max_length=50, null=True)),
                ('court_name', models.CharField(blank=True, max_length=50, null=True)),
                ('court_no', models.CharField(blank=True, max_length=50, null=True)),
                ('under_section', models.CharField(blank=True, max_length=50, null=True)),
                ('petitioner', models.CharField(blank=True, max_length=50, null=True)),
                ('respondent', models.CharField(blank=True, max_length=50, null=True)),
                ('client_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fir_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fir_year', models.CharField(blank=True, max_length=4, null=True)),
                ('police_station', models.CharField(blank=True, max_length=50, null=True)),
                ('first_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('sub_advocate', models.TextField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='media/casefiles')),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.case_type')),
                ('stage_of_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.case_stage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
