# Generated by Django 5.1.4 on 2025-01-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_case_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_master',
            name='sub_advocate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
