# Generated by Django 5.1.4 on 2025-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_alter_case_master_sub_advocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_master',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='case_master',
            name='is_desided',
            field=models.BooleanField(default=False),
        ),
    ]
