# Generated by Django 5.1.4 on 2025-01-30 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_case_master_is_active_case_master_is_desided'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate_With_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.case_master')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.clients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
