# Generated by Django 5.1.4 on 2025-02-06 03:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_associate_with_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('particular', models.TextField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/casefiles')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.case_master')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
