# Generated by Django 5.1.4 on 2025-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_casehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
