# Generated by Django 5.1.4 on 2025-02-07 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_casehistory_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('old_court', models.CharField(blank=True, max_length=50, null=True)),
                ('new_court', models.CharField(blank=True, max_length=50, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.case_master')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
